# This is a basic workflow to help you get started with Actions

name: Keep GH Maps Backend Alive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: "*/6 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: curl -X GET "https://gh-maps-backend.onrender.com"
        
